"""
Streamlit user interface and bridge to the LangGraph workflow.
"""

import streamlit as st
from langchain_core.messages import HumanMessage, AIMessage, AIMessageChunk
from graph.workflow import graph

st.set_page_config(
    page_title="EngagePro Chatbot",
    page_icon="🤖",
    layout="centered",
)

st.title("🤖 EngagePro Chatbot")

st.caption("An AI assistant for EngagePro.")

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:
    st.header("⚙️ Settings")

    st.write("Provider")
    st.info("OpenAI")

    st.write("Model")
    st.info("GPT-4.1")

    st.write("Temperature")
    st.info("0.2")

# -----------------------------
# Streamlit Session State
# preserve the conversation history while Streamlit reruns the application
# Without session state, the application would lose the conversation history between reruns.
# -----------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# -----------------------------
# Display Chat History
# -----------------------------
for message in st.session_state.messages:

    if isinstance(message, HumanMessage):
        with st.chat_message("user"):       # display the user message in the chat interface
            st.write(message.content)

    elif isinstance(message, AIMessage):
        with st.chat_message("assistant"):  # display the assistant message in the chat interface
            st.write(message.content)

# -----------------------------
# Helper Generator for Streaming
# -----------------------------
def generate_response_stream(messages: list):
    """
    Stream output tokens generated by response nodes in LangGraph.
    Yields real-time AIMessageChunk tokens for LLM generation nodes,
    and static AIMessage content for deterministic nodes (e.g., blocked_node).
    """
    for event, metadata in graph.stream({"messages": messages}, stream_mode="messages"):
        node = metadata.get("langgraph_node", "")
        if node in ("rag_chat", "general_chat", "blocked") and event.content:
            # LLM streaming node -> yield token chunks (AIMessageChunk)
            if isinstance(event, AIMessageChunk):
                yield event.content
            # Static node (e.g., blocked_node returns a fixed AIMessage) -> yield full message content
            elif isinstance(event, AIMessage) and node == "blocked":
                yield event.content

# -----------------------------
# Chat Input & Real-Time Streaming
# -----------------------------
if prompt := st.chat_input("Ask me anything..."):

    # Display user query immediately
    with st.chat_message("user"):
        st.write(prompt)

    # Save user message to session state
    st.session_state.messages.append(
        HumanMessage(content=prompt)
    )

    # Stream assistant response to UI in real time
    # st.write_stream() displays streamed output in the Streamlit UI,
    # providing a fluid, real-time typing effect.
    with st.chat_message("assistant"):
        response_text = st.write_stream(
            generate_response_stream(st.session_state.messages)
        )

    # Save assistant message to session state after streaming is complete (conversation history is preserved)
    st.session_state.messages.append(
        AIMessage(content=response_text)
    )